// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageNode_StoreShard_FullMethodName    = "/storage.StorageNode/StoreShard"
	StorageNode_RetrieveShard_FullMethodName = "/storage.StorageNode/RetrieveShard"
	StorageNode_DeleteShard_FullMethodName   = "/storage.StorageNode/DeleteShard"
	StorageNode_HealthCheck_FullMethodName   = "/storage.StorageNode/HealthCheck"
	StorageNode_GetStats_FullMethodName      = "/storage.StorageNode/GetStats"
)

// StorageNodeClient is the client API for StorageNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─── Main Service ────────────────────────────────────────────
type StorageNodeClient interface {
	StoreShard(ctx context.Context, in *StoreShardRequest, opts ...grpc.CallOption) (*StoreShardResponse, error)
	RetrieveShard(ctx context.Context, in *RetrieveShardRequest, opts ...grpc.CallOption) (*RetrieveShardResponse, error)
	DeleteShard(ctx context.Context, in *DeleteShardRequest, opts ...grpc.CallOption) (*DeleteShardResponse, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type storageNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeClient(cc grpc.ClientConnInterface) StorageNodeClient {
	return &storageNodeClient{cc}
}

func (c *storageNodeClient) StoreShard(ctx context.Context, in *StoreShardRequest, opts ...grpc.CallOption) (*StoreShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreShardResponse)
	err := c.cc.Invoke(ctx, StorageNode_StoreShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) RetrieveShard(ctx context.Context, in *RetrieveShardRequest, opts ...grpc.CallOption) (*RetrieveShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveShardResponse)
	err := c.cc.Invoke(ctx, StorageNode_RetrieveShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) DeleteShard(ctx context.Context, in *DeleteShardRequest, opts ...grpc.CallOption) (*DeleteShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShardResponse)
	err := c.cc.Invoke(ctx, StorageNode_DeleteShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, StorageNode_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, StorageNode_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServer is the server API for StorageNode service.
// All implementations must embed UnimplementedStorageNodeServer
// for forward compatibility.
//
// ─── Main Service ────────────────────────────────────────────
type StorageNodeServer interface {
	StoreShard(context.Context, *StoreShardRequest) (*StoreShardResponse, error)
	RetrieveShard(context.Context, *RetrieveShardRequest) (*RetrieveShardResponse, error)
	DeleteShard(context.Context, *DeleteShardRequest) (*DeleteShardResponse, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedStorageNodeServer()
}

// UnimplementedStorageNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageNodeServer struct{}

func (UnimplementedStorageNodeServer) StoreShard(context.Context, *StoreShardRequest) (*StoreShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreShard not implemented")
}
func (UnimplementedStorageNodeServer) RetrieveShard(context.Context, *RetrieveShardRequest) (*RetrieveShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveShard not implemented")
}
func (UnimplementedStorageNodeServer) DeleteShard(context.Context, *DeleteShardRequest) (*DeleteShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShard not implemented")
}
func (UnimplementedStorageNodeServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedStorageNodeServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedStorageNodeServer) mustEmbedUnimplementedStorageNodeServer() {}
func (UnimplementedStorageNodeServer) testEmbeddedByValue()                     {}

// UnsafeStorageNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageNodeServer will
// result in compilation errors.
type UnsafeStorageNodeServer interface {
	mustEmbedUnimplementedStorageNodeServer()
}

func RegisterStorageNodeServer(s grpc.ServiceRegistrar, srv StorageNodeServer) {
	// If the following call panics, it indicates UnimplementedStorageNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageNode_ServiceDesc, srv)
}

func _StorageNode_StoreShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).StoreShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_StoreShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).StoreShard(ctx, req.(*StoreShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_RetrieveShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).RetrieveShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_RetrieveShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).RetrieveShard(ctx, req.(*RetrieveShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_DeleteShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).DeleteShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_DeleteShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).DeleteShard(ctx, req.(*DeleteShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageNode_ServiceDesc is the grpc.ServiceDesc for StorageNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageNode",
	HandlerType: (*StorageNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreShard",
			Handler:    _StorageNode_StoreShard_Handler,
		},
		{
			MethodName: "RetrieveShard",
			Handler:    _StorageNode_RetrieveShard_Handler,
		},
		{
			MethodName: "DeleteShard",
			Handler:    _StorageNode_DeleteShard_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _StorageNode_HealthCheck_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _StorageNode_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
