// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── Store Shard ─────────────────────────────────────────────
type StoreShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ShardIndex    int32                  `protobuf:"varint,2,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	IsParity      bool                   `protobuf:"varint,5,opt,name=is_parity,json=isParity,proto3" json:"is_parity,omitempty"`
	OriginalSize  int64                  `protobuf:"varint,6,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreShardRequest) Reset() {
	*x = StoreShardRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreShardRequest) ProtoMessage() {}

func (x *StoreShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreShardRequest.ProtoReflect.Descriptor instead.
func (*StoreShardRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StoreShardRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StoreShardRequest) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

func (x *StoreShardRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoreShardRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *StoreShardRequest) GetIsParity() bool {
	if x != nil {
		return x.IsParity
	}
	return false
}

func (x *StoreShardRequest) GetOriginalSize() int64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

type StoreShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShardId       string                 `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreShardResponse) Reset() {
	*x = StoreShardResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreShardResponse) ProtoMessage() {}

func (x *StoreShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreShardResponse.ProtoReflect.Descriptor instead.
func (*StoreShardResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StoreShardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreShardResponse) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *StoreShardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─── Retrieve Shard ──────────────────────────────────────────
type RetrieveShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ShardIndex    int32                  `protobuf:"varint,2,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveShardRequest) Reset() {
	*x = RetrieveShardRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveShardRequest) ProtoMessage() {}

func (x *RetrieveShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveShardRequest.ProtoReflect.Descriptor instead.
func (*RetrieveShardRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveShardRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *RetrieveShardRequest) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

type RetrieveShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveShardResponse) Reset() {
	*x = RetrieveShardResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveShardResponse) ProtoMessage() {}

func (x *RetrieveShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveShardResponse.ProtoReflect.Descriptor instead.
func (*RetrieveShardResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveShardResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RetrieveShardResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RetrieveShardResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ─── Delete Shard ────────────────────────────────────────────
type DeleteShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ShardIndex    int32                  `protobuf:"varint,2,opt,name=shard_index,json=shardIndex,proto3" json:"shard_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShardRequest) Reset() {
	*x = DeleteShardRequest{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardRequest) ProtoMessage() {}

func (x *DeleteShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardRequest.ProtoReflect.Descriptor instead.
func (*DeleteShardRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteShardRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DeleteShardRequest) GetShardIndex() int32 {
	if x != nil {
		return x.ShardIndex
	}
	return 0
}

type DeleteShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShardResponse) Reset() {
	*x = DeleteShardResponse{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShardResponse) ProtoMessage() {}

func (x *DeleteShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShardResponse.ProtoReflect.Descriptor instead.
func (*DeleteShardResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteShardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ─── Health Check ────────────────────────────────────────────
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	StorageUsed   int64                  `protobuf:"varint,3,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	StorageTotal  int64                  `protobuf:"varint,4,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ShardCount    int32                  `protobuf:"varint,6,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthResponse) GetStorageUsed() int64 {
	if x != nil {
		return x.StorageUsed
	}
	return 0
}

func (x *HealthResponse) GetStorageTotal() int64 {
	if x != nil {
		return x.StorageTotal
	}
	return 0
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetShardCount() int32 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

// ─── Stats ───────────────────────────────────────────────────
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalReads    int64                  `protobuf:"varint,2,opt,name=total_reads,json=totalReads,proto3" json:"total_reads,omitempty"`
	TotalWrites   int64                  `protobuf:"varint,3,opt,name=total_writes,json=totalWrites,proto3" json:"total_writes,omitempty"`
	BytesStored   int64                  `protobuf:"varint,4,opt,name=bytes_stored,json=bytesStored,proto3" json:"bytes_stored,omitempty"`
	AvgLatency    float64                `protobuf:"fixed64,5,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatsResponse) GetTotalReads() int64 {
	if x != nil {
		return x.TotalReads
	}
	return 0
}

func (x *StatsResponse) GetTotalWrites() int64 {
	if x != nil {
		return x.TotalWrites
	}
	return 0
}

func (x *StatsResponse) GetBytesStored() int64 {
	if x != nil {
		return x.BytesStored
	}
	return 0
}

func (x *StatsResponse) GetAvgLatency() float64 {
	if x != nil {
		return x.AvgLatency
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\astorage\"\xbf\x01\n" +
	"\x11StoreShardRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vshard_index\x18\x02 \x01(\x05R\n" +
	"shardIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x1b\n" +
	"\tis_parity\x18\x05 \x01(\bR\bisParity\x12#\n" +
	"\roriginal_size\x18\x06 \x01(\x03R\foriginalSize\"c\n" +
	"\x12StoreShardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"P\n" +
	"\x14RetrieveShardRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vshard_index\x18\x02 \x01(\x05R\n" +
	"shardIndex\"]\n" +
	"\x15RetrieveShardResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"N\n" +
	"\x12DeleteShardRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vshard_index\x18\x02 \x01(\x05R\n" +
	"shardIndex\"/\n" +
	"\x13DeleteShardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0f\n" +
	"\rHealthRequest\"\xd3\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\fstorage_used\x18\x03 \x01(\x03R\vstorageUsed\x12#\n" +
	"\rstorage_total\x18\x04 \x01(\x03R\fstorageTotal\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vshard_count\x18\x06 \x01(\x05R\n" +
	"shardCount\"\x0e\n" +
	"\fStatsRequest\"\xb0\x01\n" +
	"\rStatsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vtotal_reads\x18\x02 \x01(\x03R\n" +
	"totalReads\x12!\n" +
	"\ftotal_writes\x18\x03 \x01(\x03R\vtotalWrites\x12!\n" +
	"\fbytes_stored\x18\x04 \x01(\x03R\vbytesStored\x12\x1f\n" +
	"\vavg_latency\x18\x05 \x01(\x01R\n" +
	"avgLatency2\xe9\x02\n" +
	"\vStorageNode\x12E\n" +
	"\n" +
	"StoreShard\x12\x1a.storage.StoreShardRequest\x1a\x1b.storage.StoreShardResponse\x12N\n" +
	"\rRetrieveShard\x12\x1d.storage.RetrieveShardRequest\x1a\x1e.storage.RetrieveShardResponse\x12H\n" +
	"\vDeleteShard\x12\x1b.storage.DeleteShardRequest\x1a\x1c.storage.DeleteShardResponse\x12>\n" +
	"\vHealthCheck\x12\x16.storage.HealthRequest\x1a\x17.storage.HealthResponse\x129\n" +
	"\bGetStats\x12\x15.storage.StatsRequest\x1a\x16.storage.StatsResponseB\tZ\a./protob\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_storage_proto_goTypes = []any{
	(*StoreShardRequest)(nil),     // 0: storage.StoreShardRequest
	(*StoreShardResponse)(nil),    // 1: storage.StoreShardResponse
	(*RetrieveShardRequest)(nil),  // 2: storage.RetrieveShardRequest
	(*RetrieveShardResponse)(nil), // 3: storage.RetrieveShardResponse
	(*DeleteShardRequest)(nil),    // 4: storage.DeleteShardRequest
	(*DeleteShardResponse)(nil),   // 5: storage.DeleteShardResponse
	(*HealthRequest)(nil),         // 6: storage.HealthRequest
	(*HealthResponse)(nil),        // 7: storage.HealthResponse
	(*StatsRequest)(nil),          // 8: storage.StatsRequest
	(*StatsResponse)(nil),         // 9: storage.StatsResponse
}
var file_storage_proto_depIdxs = []int32{
	0, // 0: storage.StorageNode.StoreShard:input_type -> storage.StoreShardRequest
	2, // 1: storage.StorageNode.RetrieveShard:input_type -> storage.RetrieveShardRequest
	4, // 2: storage.StorageNode.DeleteShard:input_type -> storage.DeleteShardRequest
	6, // 3: storage.StorageNode.HealthCheck:input_type -> storage.HealthRequest
	8, // 4: storage.StorageNode.GetStats:input_type -> storage.StatsRequest
	1, // 5: storage.StorageNode.StoreShard:output_type -> storage.StoreShardResponse
	3, // 6: storage.StorageNode.RetrieveShard:output_type -> storage.RetrieveShardResponse
	5, // 7: storage.StorageNode.DeleteShard:output_type -> storage.DeleteShardResponse
	7, // 8: storage.StorageNode.HealthCheck:output_type -> storage.HealthResponse
	9, // 9: storage.StorageNode.GetStats:output_type -> storage.StatsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
